-- Create ORDERS table
create table if not exists orders (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  status text default 'new',
  customer_name text not null,
  email text not null,
  phone text,
  fulfillment_type text not null, -- 'pickup' or 'delivery'
  address text,
  note text,
  total_cents bigint not null,
  currency text default 'EUR'
);

-- Create ORDER_ITEMS table
create table if not exists order_items (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  order_id bigint references orders(id) on delete cascade not null,
  product_id bigint references products(id), -- optional: keep reference even if product deleted? usually yes, but maybe set null
  name_snapshot text not null, -- keep name in case it changes
  price_cents_snapshot bigint not null, -- keep price
  qty int not null default 1
);

-- Enable RLS (Row Level Security) - Optionnel mais recommandé
alter table orders enable row level security;
alter table order_items enable row level security;

-- Policy: Allow anyone to insert (public checkout)
create policy "Enable insert for everyone" on orders for insert with check (true);
create policy "Enable insert for everyone" on order_items for insert with check (true);

-- Policy: Allow read only if you are the user (not implemented yet, so maybe keep public for dev or just insert-only)
-- For now, let's just allow insert. Reading usually requires admin or auth.
